package com.thomsonreuters.ccertool.vo.emerald;

import com.thomsonreuters.ccertool.vo.ProjectTypeVo;

public interface PROJECT_TYPESMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EMERALD.PROJECT_TYPES
	 * @mbggenerated  Wed Mar 16 12:16:46 CST 2016
	 */
	int deleteByPrimaryKey(Short projectTypeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EMERALD.PROJECT_TYPES
	 * @mbggenerated  Wed Mar 16 12:16:46 CST 2016
	 */
	int insert(ProjectTypeVo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EMERALD.PROJECT_TYPES
	 * @mbggenerated  Wed Mar 16 12:16:46 CST 2016
	 */
	int insertSelective(ProjectTypeVo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EMERALD.PROJECT_TYPES
	 * @mbggenerated  Wed Mar 16 12:16:46 CST 2016
	 */
	ProjectTypeVo selectByPrimaryKey(Short projectTypeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EMERALD.PROJECT_TYPES
	 * @mbggenerated  Wed Mar 16 12:16:46 CST 2016
	 */
	int updateByPrimaryKeySelective(ProjectTypeVo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EMERALD.PROJECT_TYPES
	 * @mbggenerated  Wed Mar 16 12:16:46 CST 2016
	 */
	int updateByPrimaryKey(ProjectTypeVo record);
}