package com.thomsonreuters.ccertool.vo.emerald;

import com.thomsonreuters.ccertool.vo.RepresentativesVo;

public interface REPRESENTATIVESMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EMERALD.REPRESENTATIVES
	 * @mbggenerated  Wed Mar 16 12:16:46 CST 2016
	 */
	int deleteByPrimaryKey(Short representativeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EMERALD.REPRESENTATIVES
	 * @mbggenerated  Wed Mar 16 12:16:46 CST 2016
	 */
	int insert(RepresentativesVo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EMERALD.REPRESENTATIVES
	 * @mbggenerated  Wed Mar 16 12:16:46 CST 2016
	 */
	int insertSelective(RepresentativesVo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EMERALD.REPRESENTATIVES
	 * @mbggenerated  Wed Mar 16 12:16:46 CST 2016
	 */
	RepresentativesVo selectByPrimaryKey(Short representativeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EMERALD.REPRESENTATIVES
	 * @mbggenerated  Wed Mar 16 12:16:46 CST 2016
	 */
	int updateByPrimaryKeySelective(RepresentativesVo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EMERALD.REPRESENTATIVES
	 * @mbggenerated  Wed Mar 16 12:16:46 CST 2016
	 */
	int updateByPrimaryKey(RepresentativesVo record);
}