package com.thomsonreuters.ccertool.vo;

import java.util.Date;

public class ProjectVo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMERALD.PROJECTS.PROJECT_ID
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    private Short projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMERALD.PROJECTS.MARKET_ID
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    private Short marketId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMERALD.PROJECTS.COUNTRY_STATE_ID
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    private Short countryStateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMERALD.PROJECTS.PROJECT_STAGE_ID
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    private Short projectStageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMERALD.PROJECTS.PROJECT_TYPE_ID
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    private Short projectTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMERALD.PROJECTS.METHODOLOGY_ID
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    private Short methodologyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMERALD.PROJECTS.PROJECT_NAME
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMERALD.PROJECTS.PROJECT_SUMMARY
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    private String projectSummary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMERALD.PROJECTS.PROJECT_URL
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    private String projectUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMERALD.PROJECTS.PROJECT_LOCATION
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    private String projectLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMERALD.PROJECTS.PROJECT_START_DATE
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    private Date projectStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMERALD.PROJECTS.PROJECT_END_DATE
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    private Date projectEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMERALD.PROJECTS.PROJECT_IS_STARTED
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    private Short projectIsStarted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMERALD.PROJECTS.PROJECT_INITIAL_CAPACITY
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    private Short projectInitialCapacity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMERALD.PROJECTS.PROJECT_PLANNED_CAPACITY
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    private Short projectPlannedCapacity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMERALD.PROJECTS.PROJECT_CAPACITY_COMMENT
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    private String projectCapacityComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMERALD.PROJECTS.PROJECT_INVESTOR_COMMENT
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    private String projectInvestorComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMERALD.PROJECTS.PROJECT_APPROVAL_DATE
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    private Date projectApprovalDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMERALD.PROJECTS.PROJECT_CREATED
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    private Date projectCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMERALD.PROJECTS.PROJECT_UPDATED
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    private Date projectUpdated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMERALD.PROJECTS.VISIBILITY_ID
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    private Short visibilityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMERALD.PROJECTS.PROJECT_INTERNAL_COMMENT
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    private String projectInternalComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMERALD.PROJECTS.STANDARD_ID
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    private Short standardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMERALD.PROJECTS.PROJECT_AVAILABILITY
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    private Short projectAvailability;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMERALD.PROJECTS.PROJECT_LISTING_DATE
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    private Date projectListingDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMERALD.PROJECTS.PROJECT_VERIFICATION_DATE
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    private Date projectVerificationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMERALD.PROJECTS.PROJECT_ISSUANCE_DATE
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    private Date projectIssuanceDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMERALD.PROJECTS.PRODUCT_ID
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    private Short productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMERALD.PROJECTS.PROJECT_VALIDATION_DATE
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    private Date projectValidationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMERALD.PROJECTS.PROJECT_REGISTRATION_DATE
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    private Date projectRegistrationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMERALD.PROJECTS.PROJECT_MONITORING_DATE
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    private Date projectMonitoringDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMERALD.PROJECTS.REQUEST_FOR_REGISTRATION_DATE
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    private Date requestForRegistrationDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMERALD.PROJECTS.PROJECT_ID
     *
     * @return the value of EMERALD.PROJECTS.PROJECT_ID
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public Short getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMERALD.PROJECTS.PROJECT_ID
     *
     * @param projectId the value for EMERALD.PROJECTS.PROJECT_ID
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public void setProjectId(Short projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMERALD.PROJECTS.MARKET_ID
     *
     * @return the value of EMERALD.PROJECTS.MARKET_ID
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public Short getMarketId() {
        return marketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMERALD.PROJECTS.MARKET_ID
     *
     * @param marketId the value for EMERALD.PROJECTS.MARKET_ID
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public void setMarketId(Short marketId) {
        this.marketId = marketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMERALD.PROJECTS.COUNTRY_STATE_ID
     *
     * @return the value of EMERALD.PROJECTS.COUNTRY_STATE_ID
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public Short getCountryStateId() {
        return countryStateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMERALD.PROJECTS.COUNTRY_STATE_ID
     *
     * @param countryStateId the value for EMERALD.PROJECTS.COUNTRY_STATE_ID
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public void setCountryStateId(Short countryStateId) {
        this.countryStateId = countryStateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMERALD.PROJECTS.PROJECT_STAGE_ID
     *
     * @return the value of EMERALD.PROJECTS.PROJECT_STAGE_ID
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public Short getProjectStageId() {
        return projectStageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMERALD.PROJECTS.PROJECT_STAGE_ID
     *
     * @param projectStageId the value for EMERALD.PROJECTS.PROJECT_STAGE_ID
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public void setProjectStageId(Short projectStageId) {
        this.projectStageId = projectStageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMERALD.PROJECTS.PROJECT_TYPE_ID
     *
     * @return the value of EMERALD.PROJECTS.PROJECT_TYPE_ID
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public Short getProjectTypeId() {
        return projectTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMERALD.PROJECTS.PROJECT_TYPE_ID
     *
     * @param projectTypeId the value for EMERALD.PROJECTS.PROJECT_TYPE_ID
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public void setProjectTypeId(Short projectTypeId) {
        this.projectTypeId = projectTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMERALD.PROJECTS.METHODOLOGY_ID
     *
     * @return the value of EMERALD.PROJECTS.METHODOLOGY_ID
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public Short getMethodologyId() {
        return methodologyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMERALD.PROJECTS.METHODOLOGY_ID
     *
     * @param methodologyId the value for EMERALD.PROJECTS.METHODOLOGY_ID
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public void setMethodologyId(Short methodologyId) {
        this.methodologyId = methodologyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMERALD.PROJECTS.PROJECT_NAME
     *
     * @return the value of EMERALD.PROJECTS.PROJECT_NAME
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMERALD.PROJECTS.PROJECT_NAME
     *
     * @param projectName the value for EMERALD.PROJECTS.PROJECT_NAME
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMERALD.PROJECTS.PROJECT_SUMMARY
     *
     * @return the value of EMERALD.PROJECTS.PROJECT_SUMMARY
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public String getProjectSummary() {
        return projectSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMERALD.PROJECTS.PROJECT_SUMMARY
     *
     * @param projectSummary the value for EMERALD.PROJECTS.PROJECT_SUMMARY
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public void setProjectSummary(String projectSummary) {
        this.projectSummary = projectSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMERALD.PROJECTS.PROJECT_URL
     *
     * @return the value of EMERALD.PROJECTS.PROJECT_URL
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public String getProjectUrl() {
        return projectUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMERALD.PROJECTS.PROJECT_URL
     *
     * @param projectUrl the value for EMERALD.PROJECTS.PROJECT_URL
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public void setProjectUrl(String projectUrl) {
        this.projectUrl = projectUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMERALD.PROJECTS.PROJECT_LOCATION
     *
     * @return the value of EMERALD.PROJECTS.PROJECT_LOCATION
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public String getProjectLocation() {
        return projectLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMERALD.PROJECTS.PROJECT_LOCATION
     *
     * @param projectLocation the value for EMERALD.PROJECTS.PROJECT_LOCATION
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public void setProjectLocation(String projectLocation) {
        this.projectLocation = projectLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMERALD.PROJECTS.PROJECT_START_DATE
     *
     * @return the value of EMERALD.PROJECTS.PROJECT_START_DATE
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public Date getProjectStartDate() {
        return projectStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMERALD.PROJECTS.PROJECT_START_DATE
     *
     * @param projectStartDate the value for EMERALD.PROJECTS.PROJECT_START_DATE
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public void setProjectStartDate(Date projectStartDate) {
        this.projectStartDate = projectStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMERALD.PROJECTS.PROJECT_END_DATE
     *
     * @return the value of EMERALD.PROJECTS.PROJECT_END_DATE
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public Date getProjectEndDate() {
        return projectEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMERALD.PROJECTS.PROJECT_END_DATE
     *
     * @param projectEndDate the value for EMERALD.PROJECTS.PROJECT_END_DATE
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public void setProjectEndDate(Date projectEndDate) {
        this.projectEndDate = projectEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMERALD.PROJECTS.PROJECT_IS_STARTED
     *
     * @return the value of EMERALD.PROJECTS.PROJECT_IS_STARTED
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public Short getProjectIsStarted() {
        return projectIsStarted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMERALD.PROJECTS.PROJECT_IS_STARTED
     *
     * @param projectIsStarted the value for EMERALD.PROJECTS.PROJECT_IS_STARTED
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public void setProjectIsStarted(Short projectIsStarted) {
        this.projectIsStarted = projectIsStarted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMERALD.PROJECTS.PROJECT_INITIAL_CAPACITY
     *
     * @return the value of EMERALD.PROJECTS.PROJECT_INITIAL_CAPACITY
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public Short getProjectInitialCapacity() {
        return projectInitialCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMERALD.PROJECTS.PROJECT_INITIAL_CAPACITY
     *
     * @param projectInitialCapacity the value for EMERALD.PROJECTS.PROJECT_INITIAL_CAPACITY
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public void setProjectInitialCapacity(Short projectInitialCapacity) {
        this.projectInitialCapacity = projectInitialCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMERALD.PROJECTS.PROJECT_PLANNED_CAPACITY
     *
     * @return the value of EMERALD.PROJECTS.PROJECT_PLANNED_CAPACITY
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public Short getProjectPlannedCapacity() {
        return projectPlannedCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMERALD.PROJECTS.PROJECT_PLANNED_CAPACITY
     *
     * @param projectPlannedCapacity the value for EMERALD.PROJECTS.PROJECT_PLANNED_CAPACITY
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public void setProjectPlannedCapacity(Short projectPlannedCapacity) {
        this.projectPlannedCapacity = projectPlannedCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMERALD.PROJECTS.PROJECT_CAPACITY_COMMENT
     *
     * @return the value of EMERALD.PROJECTS.PROJECT_CAPACITY_COMMENT
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public String getProjectCapacityComment() {
        return projectCapacityComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMERALD.PROJECTS.PROJECT_CAPACITY_COMMENT
     *
     * @param projectCapacityComment the value for EMERALD.PROJECTS.PROJECT_CAPACITY_COMMENT
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public void setProjectCapacityComment(String projectCapacityComment) {
        this.projectCapacityComment = projectCapacityComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMERALD.PROJECTS.PROJECT_INVESTOR_COMMENT
     *
     * @return the value of EMERALD.PROJECTS.PROJECT_INVESTOR_COMMENT
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public String getProjectInvestorComment() {
        return projectInvestorComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMERALD.PROJECTS.PROJECT_INVESTOR_COMMENT
     *
     * @param projectInvestorComment the value for EMERALD.PROJECTS.PROJECT_INVESTOR_COMMENT
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public void setProjectInvestorComment(String projectInvestorComment) {
        this.projectInvestorComment = projectInvestorComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMERALD.PROJECTS.PROJECT_APPROVAL_DATE
     *
     * @return the value of EMERALD.PROJECTS.PROJECT_APPROVAL_DATE
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public Date getProjectApprovalDate() {
        return projectApprovalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMERALD.PROJECTS.PROJECT_APPROVAL_DATE
     *
     * @param projectApprovalDate the value for EMERALD.PROJECTS.PROJECT_APPROVAL_DATE
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public void setProjectApprovalDate(Date projectApprovalDate) {
        this.projectApprovalDate = projectApprovalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMERALD.PROJECTS.PROJECT_CREATED
     *
     * @return the value of EMERALD.PROJECTS.PROJECT_CREATED
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public Date getProjectCreated() {
        return projectCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMERALD.PROJECTS.PROJECT_CREATED
     *
     * @param projectCreated the value for EMERALD.PROJECTS.PROJECT_CREATED
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public void setProjectCreated(Date projectCreated) {
        this.projectCreated = projectCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMERALD.PROJECTS.PROJECT_UPDATED
     *
     * @return the value of EMERALD.PROJECTS.PROJECT_UPDATED
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public Date getProjectUpdated() {
        return projectUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMERALD.PROJECTS.PROJECT_UPDATED
     *
     * @param projectUpdated the value for EMERALD.PROJECTS.PROJECT_UPDATED
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public void setProjectUpdated(Date projectUpdated) {
        this.projectUpdated = projectUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMERALD.PROJECTS.VISIBILITY_ID
     *
     * @return the value of EMERALD.PROJECTS.VISIBILITY_ID
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public Short getVisibilityId() {
        return visibilityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMERALD.PROJECTS.VISIBILITY_ID
     *
     * @param visibilityId the value for EMERALD.PROJECTS.VISIBILITY_ID
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public void setVisibilityId(Short visibilityId) {
        this.visibilityId = visibilityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMERALD.PROJECTS.PROJECT_INTERNAL_COMMENT
     *
     * @return the value of EMERALD.PROJECTS.PROJECT_INTERNAL_COMMENT
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public String getProjectInternalComment() {
        return projectInternalComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMERALD.PROJECTS.PROJECT_INTERNAL_COMMENT
     *
     * @param projectInternalComment the value for EMERALD.PROJECTS.PROJECT_INTERNAL_COMMENT
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public void setProjectInternalComment(String projectInternalComment) {
        this.projectInternalComment = projectInternalComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMERALD.PROJECTS.STANDARD_ID
     *
     * @return the value of EMERALD.PROJECTS.STANDARD_ID
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public Short getStandardId() {
        return standardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMERALD.PROJECTS.STANDARD_ID
     *
     * @param standardId the value for EMERALD.PROJECTS.STANDARD_ID
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public void setStandardId(Short standardId) {
        this.standardId = standardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMERALD.PROJECTS.PROJECT_AVAILABILITY
     *
     * @return the value of EMERALD.PROJECTS.PROJECT_AVAILABILITY
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public Short getProjectAvailability() {
        return projectAvailability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMERALD.PROJECTS.PROJECT_AVAILABILITY
     *
     * @param projectAvailability the value for EMERALD.PROJECTS.PROJECT_AVAILABILITY
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public void setProjectAvailability(Short projectAvailability) {
        this.projectAvailability = projectAvailability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMERALD.PROJECTS.PROJECT_LISTING_DATE
     *
     * @return the value of EMERALD.PROJECTS.PROJECT_LISTING_DATE
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public Date getProjectListingDate() {
        return projectListingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMERALD.PROJECTS.PROJECT_LISTING_DATE
     *
     * @param projectListingDate the value for EMERALD.PROJECTS.PROJECT_LISTING_DATE
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public void setProjectListingDate(Date projectListingDate) {
        this.projectListingDate = projectListingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMERALD.PROJECTS.PROJECT_VERIFICATION_DATE
     *
     * @return the value of EMERALD.PROJECTS.PROJECT_VERIFICATION_DATE
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public Date getProjectVerificationDate() {
        return projectVerificationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMERALD.PROJECTS.PROJECT_VERIFICATION_DATE
     *
     * @param projectVerificationDate the value for EMERALD.PROJECTS.PROJECT_VERIFICATION_DATE
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public void setProjectVerificationDate(Date projectVerificationDate) {
        this.projectVerificationDate = projectVerificationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMERALD.PROJECTS.PROJECT_ISSUANCE_DATE
     *
     * @return the value of EMERALD.PROJECTS.PROJECT_ISSUANCE_DATE
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public Date getProjectIssuanceDate() {
        return projectIssuanceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMERALD.PROJECTS.PROJECT_ISSUANCE_DATE
     *
     * @param projectIssuanceDate the value for EMERALD.PROJECTS.PROJECT_ISSUANCE_DATE
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public void setProjectIssuanceDate(Date projectIssuanceDate) {
        this.projectIssuanceDate = projectIssuanceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMERALD.PROJECTS.PRODUCT_ID
     *
     * @return the value of EMERALD.PROJECTS.PRODUCT_ID
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public Short getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMERALD.PROJECTS.PRODUCT_ID
     *
     * @param productId the value for EMERALD.PROJECTS.PRODUCT_ID
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public void setProductId(Short productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMERALD.PROJECTS.PROJECT_VALIDATION_DATE
     *
     * @return the value of EMERALD.PROJECTS.PROJECT_VALIDATION_DATE
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public Date getProjectValidationDate() {
        return projectValidationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMERALD.PROJECTS.PROJECT_VALIDATION_DATE
     *
     * @param projectValidationDate the value for EMERALD.PROJECTS.PROJECT_VALIDATION_DATE
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public void setProjectValidationDate(Date projectValidationDate) {
        this.projectValidationDate = projectValidationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMERALD.PROJECTS.PROJECT_REGISTRATION_DATE
     *
     * @return the value of EMERALD.PROJECTS.PROJECT_REGISTRATION_DATE
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public Date getProjectRegistrationDate() {
        return projectRegistrationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMERALD.PROJECTS.PROJECT_REGISTRATION_DATE
     *
     * @param projectRegistrationDate the value for EMERALD.PROJECTS.PROJECT_REGISTRATION_DATE
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public void setProjectRegistrationDate(Date projectRegistrationDate) {
        this.projectRegistrationDate = projectRegistrationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMERALD.PROJECTS.PROJECT_MONITORING_DATE
     *
     * @return the value of EMERALD.PROJECTS.PROJECT_MONITORING_DATE
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public Date getProjectMonitoringDate() {
        return projectMonitoringDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMERALD.PROJECTS.PROJECT_MONITORING_DATE
     *
     * @param projectMonitoringDate the value for EMERALD.PROJECTS.PROJECT_MONITORING_DATE
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public void setProjectMonitoringDate(Date projectMonitoringDate) {
        this.projectMonitoringDate = projectMonitoringDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMERALD.PROJECTS.REQUEST_FOR_REGISTRATION_DATE
     *
     * @return the value of EMERALD.PROJECTS.REQUEST_FOR_REGISTRATION_DATE
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public Date getRequestForRegistrationDate() {
        return requestForRegistrationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMERALD.PROJECTS.REQUEST_FOR_REGISTRATION_DATE
     *
     * @param requestForRegistrationDate the value for EMERALD.PROJECTS.REQUEST_FOR_REGISTRATION_DATE
     *
     * @mbggenerated Wed Feb 17 15:38:29 CST 2016
     */
    public void setRequestForRegistrationDate(Date requestForRegistrationDate) {
        this.requestForRegistrationDate = requestForRegistrationDate;
    }
}