package com.thomsonreuters.ccertool.vo;

import java.io.InputStream;

public class ProjectDocumentVo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMERALD.PROJECT_DOCUMENTS.PROJECT_DOCUMENT_ID
     *
     * @mbggenerated Wed Feb 17 15:40:46 CST 2016
     */
    private int projectDocumentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMERALD.PROJECT_DOCUMENTS.PROJECT_ID
     *
     * @mbggenerated Wed Feb 17 15:40:46 CST 2016
     */
    private int projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMERALD.PROJECT_DOCUMENTS.REPORT_FILE_NAME
     *
     * @mbggenerated Wed Feb 17 15:40:46 CST 2016
     */
    private String reportFileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMERALD.PROJECT_DOCUMENTS.REPORT_FILE_CONTENT_TYPE
     *
     * @mbggenerated Wed Feb 17 15:40:46 CST 2016
     */
    private String reportFileContentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMERALD.PROJECT_DOCUMENTS.PROJECT_DOCUMENT_TYPE_ID
     *
     * @mbggenerated Wed Feb 17 15:40:46 CST 2016
     */
    private int projectDocumentTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMERALD.PROJECT_DOCUMENTS.REPORT_FILE_CONTENT
     *
     * @mbggenerated Wed Feb 17 15:40:46 CST 2016
     */
    private InputStream reportFileContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMERALD.PROJECT_DOCUMENTS.PROJECT_DOCUMENT_ID
     *
     * @return the value of EMERALD.PROJECT_DOCUMENTS.PROJECT_DOCUMENT_ID
     *
     * @mbggenerated Wed Feb 17 15:40:46 CST 2016
     */
    public int getProjectDocumentId() {
        return projectDocumentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMERALD.PROJECT_DOCUMENTS.PROJECT_DOCUMENT_ID
     *
     * @param projectDocumentId the value for EMERALD.PROJECT_DOCUMENTS.PROJECT_DOCUMENT_ID
     *
     * @mbggenerated Wed Feb 17 15:40:46 CST 2016
     */
    public void setProjectDocumentId(int projectDocumentId) {
        this.projectDocumentId = projectDocumentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMERALD.PROJECT_DOCUMENTS.PROJECT_ID
     *
     * @return the value of EMERALD.PROJECT_DOCUMENTS.PROJECT_ID
     *
     * @mbggenerated Wed Feb 17 15:40:46 CST 2016
     */
    public int getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMERALD.PROJECT_DOCUMENTS.PROJECT_ID
     *
     * @param projectId the value for EMERALD.PROJECT_DOCUMENTS.PROJECT_ID
     *
     * @mbggenerated Wed Feb 17 15:40:46 CST 2016
     */
    public void setProjectId(int projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMERALD.PROJECT_DOCUMENTS.REPORT_FILE_NAME
     *
     * @return the value of EMERALD.PROJECT_DOCUMENTS.REPORT_FILE_NAME
     *
     * @mbggenerated Wed Feb 17 15:40:46 CST 2016
     */
    public String getReportFileName() {
        return reportFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMERALD.PROJECT_DOCUMENTS.REPORT_FILE_NAME
     *
     * @param reportFileName the value for EMERALD.PROJECT_DOCUMENTS.REPORT_FILE_NAME
     *
     * @mbggenerated Wed Feb 17 15:40:46 CST 2016
     */
    public void setReportFileName(String reportFileName) {
        this.reportFileName = reportFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMERALD.PROJECT_DOCUMENTS.REPORT_FILE_CONTENT_TYPE
     *
     * @return the value of EMERALD.PROJECT_DOCUMENTS.REPORT_FILE_CONTENT_TYPE
     *
     * @mbggenerated Wed Feb 17 15:40:46 CST 2016
     */
    public String getReportFileContentType() {
        return reportFileContentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMERALD.PROJECT_DOCUMENTS.REPORT_FILE_CONTENT_TYPE
     *
     * @param reportFileContentType the value for EMERALD.PROJECT_DOCUMENTS.REPORT_FILE_CONTENT_TYPE
     *
     * @mbggenerated Wed Feb 17 15:40:46 CST 2016
     */
    public void setReportFileContentType(String reportFileContentType) {
        this.reportFileContentType = reportFileContentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMERALD.PROJECT_DOCUMENTS.PROJECT_DOCUMENT_TYPE_ID
     *
     * @return the value of EMERALD.PROJECT_DOCUMENTS.PROJECT_DOCUMENT_TYPE_ID
     *
     * @mbggenerated Wed Feb 17 15:40:46 CST 2016
     */
    public int getProjectDocumentTypeId() {
        return projectDocumentTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMERALD.PROJECT_DOCUMENTS.PROJECT_DOCUMENT_TYPE_ID
     *
     * @param projectDocumentTypeId the value for EMERALD.PROJECT_DOCUMENTS.PROJECT_DOCUMENT_TYPE_ID
     *
     * @mbggenerated Wed Feb 17 15:40:46 CST 2016
     */
    public void setProjectDocumentTypeId(int projectDocumentTypeId) {
        this.projectDocumentTypeId = projectDocumentTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMERALD.PROJECT_DOCUMENTS.REPORT_FILE_CONTENT
     *
     * @return the value of EMERALD.PROJECT_DOCUMENTS.REPORT_FILE_CONTENT
     *
     * @mbggenerated Wed Feb 17 15:40:46 CST 2016
     */
    public InputStream getReportFileContent() {
        return reportFileContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMERALD.PROJECT_DOCUMENTS.REPORT_FILE_CONTENT
     *
     * @param reportFileContent the value for EMERALD.PROJECT_DOCUMENTS.REPORT_FILE_CONTENT
     *
     * @mbggenerated Wed Feb 17 15:40:46 CST 2016
     */
    public void setReportFileContent(InputStream reportFileContent) {
        this.reportFileContent = reportFileContent;
    }
}